export const SYMPTOM_CHECK_REQUEST = "SYMPTOM_CHECK_REQUEST";
export const SYMPTOM_CHECK_SUCCESS = "SYMPTOM_CHECK_SUCCESS";
export const SYMPTOM_CHECK_FAILURE = "SYMPTOM_CHECK_FAILURE";
export const SYMPTOM_CHECK_CLEAR = "SYMPTOM_CHECK_CLEAR";
